sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "S5W0KDsCn4SVuTiVlLQjlUWtJB9nE56DVJeUI3Aq8jV40k8jWEf3R84spKEDf/ov0shmsymGB434+StLWLk5wA1l+mSrtVWuyEnS0K6SZRuuS8QDKMKN8zCPXaXOtyh/8gBh1uUWn/2giGd7w9ZfW7KyzSv5o/LaMDRKK2Z/0xguX5Cmf1JGNy8+EgJsf0oLbklDeojSwMEuV+Ig7edI0bsXbTi99HrWG5kLIY6MyKBsbQbTMnVRXq0BjvMW7q4/dhOIHovN/A5gF+6RgS73XHWm4xgQmBvufOl3e+/gUOYMjoTPAL0NqYsc9cXWxYvdhpEYwO88ua5Jv9lho4evqbvcWWx3Ov2775oHSML8gP6bZStEXS0xpRuZKquQIfLb6llu+530Ff3lPDBbnDHFjKiTyS2T3rWUPgWAqRnzFCThqXlSRj/HEMQeicId1iP9MFY7I0DMLT9qpj2Pbp7k4oE46c4uuLZix4vpYB1mkLcjdbsI/TIAtoXPpMZrRotnDAoKUuhCCtGQgTmnJ0GnU/WOaUHsKFhtatnhdTWsl1YJ4rh0Klc5734dwGjKJK++eslp0jzWaL0TsuBln4UuLa7UXkVbrGcMTDLYT8toQs7mh3QCcxEhstaGz9L7MCoNkcJ73FLVjMTN3+CwMmeoxGQWYroO7NAYS2v7z3eUVFA="
  # Ex. travis encrypt -r org/repo SONATYPE_USERNAME=your_sonatype_account
  - secure: "KJWLpbot+7TFzcpwjJUH5qIDP1b1tcEEBnx57CiNsQEIrdbCRR3xkILsTUG+tllTWW5jv/TQcE0BN76009WAWEzOFiHtHyNKjAUrnQytAiHZbdyCTI75G6LFOPhXLwz1e0AfPi0SzwdRHsFObPkPZ0chzsPITfDJJG9WrfzuTwBpfdgOnZ0rRk1w0RYjT728jS2lnX9ojb3iW0221Ug5gbL0brxzfghs8zMidfvUy7ufBx9lnSNvlDIe2LTlIb/ZVKUQlauSufIb0KgTVg+Ljj0+H+qucskT3DgHnQpGqEAea75LIospeTg5dTv+5BlWO4B3F+yAAcPnVaOO+gkm1riL23NImRQmlf+BKDuVo1Gl7XCDP6L2jbYmG7j+LnIyXXM31mjTqyubWotsE59y2yn1bOtrmYb9V/U3r9Lx65+a61TMpaEK9JBf0s7piRThDDHrFbKeozkotZTFW3gZB1SnNkMeVSV+IsI74FkHds6fuwCxtgmrG59qfearNp8vlSeQ+0yf8gEj4ga8vpO+35TOASEsNsQJkBLBlAMs9RExjMl7If5O5rhNYEpMfsO+NxG9NxYxBJhyAMGDKv4tFUpsLpeAzBeScdDih5CNscTfHQXMxFzZJ/aE/wGnBhDzdYSY81TEX1zE1wuFCZEuiioQaGOojRBM5f+sn4mL5VQ="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "N518K+MCYXpzqZNhPa/cvhNjg7N8oD50rPNGsmzqahAHygk7j2AcJoNNC6FBWH1zpZ+V8Z2yfpUAsRsePHvQrYGcLPUll3KZi50579+pBxZqiFYToobScdwofHre15q9FCrT1qwUUcsOdHrhdqzCeALsi3YMYjbzbX8lucAlNI2FYc4PmpkpVmpjDRlBYasA29IcVJ1eKEiBJdXO2OtFAKh5MSLI10GqovE7xkpjdGjMnDsZZnhIeBX2ZW2+D0Q7UdfT3iGuU/YFnOcAOLlxmGenB01K7wKhJ6Yi4kreQarVtx3quXkjXMebMRdEQgZmgPVQULn1LZNG+kJLA+ABwN/8MELjD3FBdC7d041HLM+lEPFFtUv3oVqs6Z+ev1IqoCZKJKkRghpcA0BYIJyC/Pb+kmZNYh+P0KW2iEF7kVBLho7brNQSfdnPDee77LnvFofeIkVqiw+kIiELuu16c6kBKw6W5vJv16udldA488zrt7LqFdrrJdihQWTKlKipaKWvsltoMvvrL3h+UeUAo2gudCpdc5zoxlrJVUotLifYYS2xLxH50pkSy/G1tN60Z5Dlcd0CMwzcs/fm3TF9/Q+UXqrbsMm4N4klGSTrXG4p14a15R9aI+OQgl3tDEzATVqUnWOClUp0SHM5NVFFagrvM8QHrZ2VVOtNkOIsqNc="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "IR8agG8QAKPR0bn4svug3NbN34E7faCKGuKa0liWyW8jCbgRh69EVhI6UzmbwmbAu84icIArKpH9ofkmA0I3xhKzZoR8+q2waCudPl2yrq0AZB+aKHiSmcXxARv3qsFJTwMsHnezB2jBekhenA4arZQ2TQNvGh4ERHxyEAq2e2QYT72CnlN75nq3Gtt/O3nKUoBom1scVsj1db8Y2HpPWQ4SQmrDPOeYXT6DI3hN6G+8A8HSfk5j0oHExdcCO3uuKQCX+wNCpoNbtjHWoTTnPoxScii5B27y5RjN+LaL0YA8UeD5wdesxc894gBXH1RUo21RgsfqsGkH2Hg7mTNrKHUCu77AUzhL8cW2+yGaHbmmKFrtdfDVeA4t2r6t/3PtGBuPMsnThm70sb0Y4rEW86Kkr7g7k2Nxh+VEdf7DN2ZKMqG1mGtYQteZaqmU4eg9I40ArXZpFv3GDEkgJWAInpyNVKfNAnCcFfmdC4VdKZq8sabOGfMutYLkyLG2JIQiqYhmxOrXuMFF6uXU3GL79y1WAVhkOm6TG77QwlWBg0cPEPbbbBAV8LBcREIHn0EKDaSV3i4DmfB+RN1OjqPWRNUW39RMDJT4eLYN12poojLfPfQnBXjVnoYiF1DyEJRfSdLyTrAhxfvwhUtSaH7BQHJUE4NJBI06nSAb/KBbMzM="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "kaMMrxLj8Cx2tJh+pzE0gKbWfazem2G3XaMw2XkrPdTXr7eF59vXbqI7LH93hgUCAWl5gTmdyNNxLD8ED3E5fr4EAPN4c74J261awF+CMLAtH57LRC3q4otqpbnI9cyi7PpHXvD2Qioc3S73+rX4gjxRClkUFrMXGUjr3cmGEAMwLf6KMP5eCQzLbxyjJVwFhajcxTbTy9lKy0tUgX6e1+0Md2WD6sr7UnZNTbSzxAk6evkpQ/ZMEpXK3PznYIs6s8rxMX054NpJQC7Zkb/0w30WemLtLVZjmLxpL4idSpScLCDYCuYWWz7y2nK1frS0ZIuQP8vdJYWBNjLSlwAKQe+UvZUoHQAc6k3CZFePTOYeCluhn5hwJ1paM0GzMUgpjFnz2HfUOVHkrU2RK9jwcx9v5bUaDPORtaXHGt5SQbhYDPCX9aqxRNUOTaj9XYP4H/8HeK/LZStT92Sl3RNKDVjb3hnNA7bqcQSlQVWAxstLp50zqSC+bB9SYm96QBW1EVafTkkDuTAgIxcE2oJUB1rOWileT9v0/hS5eos17uPR9wRU5OOqcrmLSh9i+GGvqXiVeg2Sz+Nenh1Khx6ZMwyjzZ8RDfgAMCoLmsRi4vZ3KgvRD5tnfYLuoPXemyaNbXHrY32D7NF9aqT5bU+wC0JS0ab1esKrob5atl9VjYk="
